# Generated by Django 3.0.4 on 2020-04-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20200416_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='image',
            field=models.ImageField(default='pepporoni.jpg', upload_to='topimages'),
        ),
    ]
