# Generated by Django 3.0.4 on 2020-04-16 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20200416_0336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
