# Generated by Django 3.0.6 on 2020-05-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_pizza_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='flavour',
            field=models.CharField(choices=[('cheese', 'cheese'), ('1-topping', '1-topping'), ('2-toppings', '2-toppings'), ('3-toppings', '3-toppings')], max_length=20),
        ),
    ]
